# Generated by Django 4.2.6 on 2023-12-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('last_digits', models.SmallIntegerField()),
            ],
        ),
    ]
