# Generated by Django 4.2.6 on 2023-12-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
