# Generated by Django 4.2.6 on 2023-12-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_min_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
