# Generated by Django 4.2.6 on 2023-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
