# Generated by Django 4.2.6 on 2023-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to='uploads/images_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(unique=True, upload_to='uploads/images_product/'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
