# Generated by Django 4.2.6 on 2023-11-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='rgb',
        ),
    ]
