# Generated by Django 3.2.1 on 2023-12-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20231230_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
