# Generated by Django 4.2.6 on 2023-10-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True),
        ),
    ]
