# Generated by Django 4.2.6 on 2023-12-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_rename_primary_address_shippingaddress_default_address'),
        ('order', '0002_rename_date_ordered_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shipping.shippingaddress'),
        ),
    ]
