# Generated by Django 4.2.6 on 2023-11-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_remove_shippingaddress_city_and_more'),
        ('order', '0002_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shipping.shippingaddress'),
        ),
    ]
