# Generated by Django 4.2.6 on 2023-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
