# Generated by Django 3.2.1 on 2023-12-30 21:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productorder_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_order_image'),
        ),
    ]
