# Generated by Django 4.2.6 on 2023-12-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_productorder_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_id',
        ),
    ]
