# Generated by Django 4.2.6 on 2023-11-21 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=16)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(8)])),
                ('primary_address', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
