# Generated by Django 4.2.6 on 2023-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address1', models.CharField(blank=True, max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
