# Generated by Django 4.2.6 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='primary_address',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
