# Generated by Django 4.2.6 on 2023-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shippingaddress_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
