# Generated by Django 4.2.6 on 2023-11-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
