# Generated by Django 4.2.6 on 2023-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
