# Generated by Django 4.2.6 on 2023-12-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
